### ISSUE TITLE
Problems arising from outdated clones

### ISSUE THREAD

**Issue by kostirez1** [ajgon/bgtoolset#11] opened 2022-10-26 12:06 UTC
Ignoring the fact that this dump often lands in the hands of bad people, there are some people who are hosting it with good intentions for the public. There are problems arising from this though. Mainly because there's no version check to see if there isn't a newer version available. Users might end up with bricked consoles in cases like this.

Would it be possible to add a time bomb to prevent outdated copies of this repo from functioning? Something that would disable the ability to load the website or to patch the flash after let's say 30 days since the time it was last updated, or cloned in this case.

**Comment by ajgon** [comment] 2022-10-26 16:38
The problem is, everything is client side. So this "time bomb" will be trivial to disarm. Also, I don't want to spend too much time on this.

To be honest, I'm starting to think, that I should close this repo, as it actually does more harm than good...

**Closed by ajgon** 2022-10-26 16:38 UTC

**Comment by kostirez1** [comment] 2022-10-27 12:28
I agree that limiting the number of ways to get a clone of bgtoolset is ultimately the best solution. Especially considering the copyright reasons. But I'm not the one who should decide, or force it.

If that wouldn't happen though, please still consider implementing some kind of a trivial protection. Even if it's easy to remove, at least it makes hosting it publicly a deliberate choice, accepting that users are being at risk. I'm sure there were some clones that unknowingly did this.
